### ISSUE TITLE
Add datasets

### ISSUE THREAD

**Issue by luis-gustavo** [deeplearningunb/Sign-Language-Digits-Detector#7]
## Description

Add the datasets that will be used in this project.

**Comment by Felizolinha** [comment]
The base dataset will be the [Sign Language Digits Dataset](https://github.com/ardamavi/Sign-Language-Digits-Dataset). There is a script to get it and use it in python [here](https://gist.github.com/ardamavi/a7d06ff8a315308771c70006cf494d69), but it needs some adaptation before using, as mentioned in the comments of the gist.

**Comment by Felizolinha** [comment]
To prevent a bias towards white backgrounds and specific hand colors, we can try applying style transfer to the images. This technique helps CNNs detect shapes intead of textures, we can try measuring it's effect on the Capsule Network training. [Paper demonstrating the generalization benefits for CNNs.](http://www.insticc.org/Primoris/Resources/PaperPdf.ashx?idPaper=73534)
